/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punching;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

/**
 *
 * @author admin
 */
public class TemplateFrame extends javax.swing.JFrame {

    /**
     * Creates new form TemplateFrame
     */
    public TemplateFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupA = new javax.swing.ButtonGroup();
        buttonGroupB = new javax.swing.ButtonGroup();
        btnClose = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnSetTemplateFolder = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSaveAs = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtObjectLength = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHolesA = new punching.MyTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHolesB = new punching.MyTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboListTemplate = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCopyToB = new javax.swing.JButton();
        btnAddA = new javax.swing.JButton();
        btnRemoveA = new javax.swing.JButton();
        btnAddB = new javax.swing.JButton();
        btnRemoveB = new javax.swing.JButton();
        radAY = new javax.swing.JRadioButton();
        radAX = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radBX = new javax.swing.JRadioButton();
        radBY = new javax.swing.JRadioButton();
        lblTemplateFolder = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTemplateFile = new javax.swing.JLabel();
        txtObjectWidth = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        drawPanel = new punching.ObjectDrawPanel();
        jToolBar3 = new javax.swing.JToolBar();
        btnZoomIn = new javax.swing.JButton();
        btnZoomOut = new javax.swing.JButton();
        chkShowPositionText = new javax.swing.JCheckBox();

        setTitle("Tạo Mẫu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1421449836_Log Out.png"))); // NOI18N
        btnClose.setText("Đóng");
        btnClose.setToolTipText("");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnSetTemplateFolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1427532611_open-file.png"))); // NOI18N
        btnSetTemplateFolder.setText("Open");
        btnSetTemplateFolder.setToolTipText("Chọn thư mục chứa mẫu");
        btnSetTemplateFolder.setFocusable(false);
        btnSetTemplateFolder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetTemplateFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTemplateFolderActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSetTemplateFolder);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1421449948_document-new.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.setToolTipText("Tạo mẫu mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1421449682_save-16.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Lưu trữ vào thư viện mẫu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1427531293_save_all.png"))); // NOI18N
        btnSaveAs.setText("Save As");
        btnSaveAs.setToolTipText("Lưu thành mẫu khác");
        btnSaveAs.setFocusable(false);
        btnSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveAs);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1427531714_trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Xóa mẫu");
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Chiều dài:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên:");

        txtObjectLength.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtObjectLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObjectLengthActionPerformed(evt);
            }
        });
        txtObjectLength.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObjectLengthFocusLost(evt);
            }
        });

        tblHolesA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHolesA.setCellSelectionEnabled(true);
        tblHolesA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHolesA.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHolesA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblHolesAFocusLost(evt);
            }
        });
        tblHolesA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblHolesAKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblHolesA);

        tblHolesB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHolesB.setCellSelectionEnabled(true);
        tblHolesB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHolesB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHolesB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblHolesBFocusLost(evt);
            }
        });
        tblHolesB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblHolesBKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblHolesB);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Mặt A");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Mặt B");

        cboListTemplate.setModel(getTemplateModel());
        cboListTemplate.setRenderer(new ComboBoxRenderer());
        cboListTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboListTemplateActionPerformed(evt);
            }
        });

        jLabel3.setText("Chọn mẫu cần sửa:");

        txtName.setText("Name");

        btnCopyToB.setText(">>");
        btnCopyToB.setToolTipText("Chép sang mặt B");
        btnCopyToB.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCopyToB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyToBActionPerformed(evt);
            }
        });

        btnAddA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1420490265_add.png"))); // NOI18N
        btnAddA.setToolTipText("Thêm 1 lổ đột");
        btnAddA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAddA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAActionPerformed(evt);
            }
        });

        btnRemoveA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1420490314_minus-16.png"))); // NOI18N
        btnRemoveA.setToolTipText("Xóa lổ đột");
        btnRemoveA.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnRemoveA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAActionPerformed(evt);
            }
        });

        btnAddB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1420490265_add.png"))); // NOI18N
        btnAddB.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnAddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBActionPerformed(evt);
            }
        });

        btnRemoveB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1420490314_minus-16.png"))); // NOI18N
        btnRemoveB.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnRemoveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveBActionPerformed(evt);
            }
        });

        buttonGroupA.add(radAY);
        radAY.setText("Y");

        buttonGroupA.add(radAX);
        radAX.setSelected(true);
        radAX.setText("X");

        jLabel6.setText("Cố định");

        jLabel7.setText("Cố định");

        buttonGroupB.add(radBX);
        radBX.setSelected(true);
        radBX.setText("X");

        buttonGroupB.add(radBY);
        radBY.setText("Y");

        lblTemplateFolder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTemplateFolder.setText("D:\\");

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
            jLabel8.setText("Thư mục mẫu:");

            lblTemplateFile.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
            lblTemplateFile.setText("D:\\");

                txtObjectWidth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
                txtObjectWidth.addFocusListener(new java.awt.event.FocusAdapter() {
                    public void focusLost(java.awt.event.FocusEvent evt) {
                        txtObjectWidthFocusLost(evt);
                    }
                });

                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                jLabel9.setText("Bề rộng:");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObjectWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObjectLength, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAddA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoveA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radAX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radAY))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCopyToB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAddB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRemoveB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radBX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radBY))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel4)
                                .addGap(194, 194, 194)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboListTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTemplateFile, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTemplateFolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                );

                jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtName, txtObjectLength, txtObjectWidth});

                jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddA, btnAddB, btnRemoveA, btnRemoveB});

                jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemplateFolder)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cboListTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTemplateFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(txtObjectLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnCopyToB, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtObjectWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 214, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddA)
                            .addComponent(btnRemoveA)
                            .addComponent(btnAddB)
                            .addComponent(btnRemoveB)
                            .addComponent(radAY)
                            .addComponent(radAX)
                            .addComponent(jLabel6)
                            .addComponent(radBY)
                            .addComponent(radBX)
                            .addComponent(jLabel7)))
                );

                jTabbedPane1.addTab("Soạn mẫu", jPanel2);

                jPanel3.setRequestFocusEnabled(false);

                javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
                drawPanel.setLayout(drawPanelLayout);
                drawPanelLayout.setHorizontalGroup(
                    drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 752, Short.MAX_VALUE)
                );
                drawPanelLayout.setVerticalGroup(
                    drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 418, Short.MAX_VALUE)
                );

                jScrollPane1.setViewportView(drawPanel);

                jToolBar3.setRollover(true);

                btnZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1428185613_magnifier_zoom_in.png"))); // NOI18N
                btnZoomIn.setFocusable(false);
                btnZoomIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnZoomIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnZoomIn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnZoomInActionPerformed(evt);
                    }
                });
                jToolBar3.add(btnZoomIn);

                btnZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1428185566_zoom_out.png"))); // NOI18N
                btnZoomOut.setFocusable(false);
                btnZoomOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnZoomOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnZoomOut.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnZoomOutActionPerformed(evt);
                    }
                });
                jToolBar3.add(btnZoomOut);

                chkShowPositionText.setSelected(true);
                chkShowPositionText.setText("Xem tọa độ");
                chkShowPositionText.setFocusable(false);
                chkShowPositionText.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                chkShowPositionText.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                chkShowPositionText.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        chkShowPositionTextActionPerformed(evt);
                    }
                });
                jToolBar3.add(chkShowPositionText);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Xem mẫu", jPanel3);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 413, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClose)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose)
                        .addContainerGap())
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     *
     * @param newFile true to Save as
     */
    private void save(boolean newFile) {
        try {
            Template template = (Template) cboListTemplate.getSelectedItem();
            template.setLength(Float.parseFloat(txtObjectLength.getText()));
            template.setXmax(Float.parseFloat(txtObjectWidth.getText()));
            template.setName(txtName.getText());
            if (template.getFileName() == null || newFile) { // save to new file
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Template file (.xml)", "xml");
                JFileChooser fc = new JFileChooser(environment.getSetting().getTemplateFolder());
                fc.setFileFilter(filter);
                int returnVal = fc.showSaveDialog(this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    String path = fc.getSelectedFile().getAbsolutePath();
                    if (!path.contains(".")) {
                        path = path + ".xml";
                    }
                    if (new File(path).exists()) {
                        int dialogResult = JOptionPane.showConfirmDialog(null, "Overwrite?", "Warning", JOptionPane.YES_NO_OPTION);
                        if (dialogResult == JOptionPane.NO_OPTION) {
                            return;
                        }
                    }
                    template.setFileName(path);
                }
            }

            // Save to file
            JAXBContext context = JAXBContext.newInstance(Template.class);
            Marshaller m = context.createMarshaller();
            m.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
            m.marshal(template, System.out);
            String path = template.getFileName();
            FileOutputStream fo = new FileOutputStream(path);
            m.marshal(template, fo);
            fo.close();
            JOptionPane.showMessageDialog(this, "Đã lưu mẫu.");
            isDirty = false;

            //reload template list
            Environment.reloadTemplate();
            cboListTemplate.setModel(getTemplateModel());
            onTemplateFolderChange(template.getFileName());

        } catch (IOException ex) {
            Logger.getLogger(TemplateFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JAXBException ex) {
            Logger.getLogger(TemplateFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void cboListTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboListTemplateActionPerformed
        checkAndSave();

        Template template = (Template) cboListTemplate.getSelectedItem();

        lblTemplateFile.setText(template.getFileName());
        txtName.setText(template.getName());
        txtObjectLength.setValue(template.getLength());

        // for old template (without width), calculate it
        if (template.getXmax() <= 0) {
            float max = 0;
            for (Hole a : template.getFaceAHoles()) {
                if (a.getX() > max) {
                    max = a.getX();
                }
            }
            for (Hole b : template.getFaceBHoles()) {
                if (b.getX() > max) {
                    max = b.getX();
                }
            }
            max = max + 10; // add 10
            txtObjectWidth.setValue(max);
        } else {
            txtObjectWidth.setValue(template.getXmax());
        }

        HoleTableModel modelA = new HoleTableModel(template.getFaceAHoles(), "A");
        modelA.setXmax(template.getXmax());
        modelA.updateYR();
        tblHolesA.setModel(modelA);
        HoleTableModel modelB = new HoleTableModel(template.getFaceBHoles(), "B");
        modelB.setXmax(template.getXmax());
        modelB.updateYR();
        tblHolesB.setModel(modelB);

        drawPanel.setTemplate(template);

        // for single click, combo editor,...
        setCustomTableEditors();
    }//GEN-LAST:event_cboListTemplateActionPerformed

    private void tblHolesAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblHolesAKeyPressed
//        HoleTableModel model = (HoleTableModel) tblHolesA.getModel();
//        if (evt.getKeyCode() == KeyEvent.VK_INSERT && evt.isControlDown()) {
//            model.addRow(radAX.isSelected(), step);
//        }
//        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
//            int rowIndex = tblHolesA.getSelectedRow();
//            if (rowIndex >= 0) {
//                model.removeRow(rowIndex);
//            }
//        }
    }//GEN-LAST:event_tblHolesAKeyPressed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        TemplateModel model = (TemplateModel) cboListTemplate.getModel();
        Template template = new Template("Mẫu ABC", 3000, 200);
        model.addElement(template);
        template.getFaceAHoles().add(new Hole(50, 50, environment.getSetting().getFaceATools().get(0)));
        cboListTemplate.setSelectedItem(template);
        isDirty = true;

        // for single click, combo editor,...
        setCustomTableEditors();
    }//GEN-LAST:event_btnNewActionPerformed

    private void tblHolesBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblHolesBKeyPressed
//        HoleTableModel model = (HoleTableModel) tblHolesB.getModel();
//        if (evt.getKeyCode() == KeyEvent.VK_INSERT && evt.isControlDown()) {
//            model.addRow(radBX.isSelected(), step);
//        }
//        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
//            int rowIndex = tblHolesB.getSelectedRow();
//            if (rowIndex >= 0) {
//                model.removeRow(rowIndex);
//            }
//        }
    }//GEN-LAST:event_tblHolesBKeyPressed

    private void btnCopyToBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyToBActionPerformed
        Template template = (Template) cboListTemplate.getSelectedItem();
        template.getFaceBHoles().clear();
        for (Hole holeA : template.getFaceAHoles()) {
            Tool t = Environment.getToolByName(holeA.getT().getName(), "B");
            template.getFaceBHoles().add(new Hole(holeA.getY(), holeA.getX(), t));
        }
        HoleTableModel modelB = new HoleTableModel(template.getFaceBHoles(), "B");
        tblHolesB.setModel(modelB);
        reloadDisplay();
    }//GEN-LAST:event_btnCopyToBActionPerformed

    private void btnRemoveAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAActionPerformed
        int rowIndex = tblHolesA.getSelectedRow();
        if (rowIndex >= 0) {
            HoleTableModel model = (HoleTableModel) tblHolesA.getModel();
            model.removeRow(rowIndex);
        }
        reloadDisplay();
    }//GEN-LAST:event_btnRemoveAActionPerformed

    private void btnAddAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAActionPerformed
        HoleTableModel model = (HoleTableModel) tblHolesA.getModel();
        model.addRow(radAX.isSelected(), step);
        reloadDisplay();
    }//GEN-LAST:event_btnAddAActionPerformed

    private void btnAddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBActionPerformed
        HoleTableModel model = (HoleTableModel) tblHolesB.getModel();
        model.addRow(radBX.isSelected(), step);
        reloadDisplay();
    }//GEN-LAST:event_btnAddBActionPerformed

    private void btnRemoveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveBActionPerformed
        int rowIndex = tblHolesB.getSelectedRow();
        if (rowIndex >= 0) {
            HoleTableModel model = (HoleTableModel) tblHolesB.getModel();
            model.removeRow(rowIndex);
        }
        reloadDisplay();
    }//GEN-LAST:event_btnRemoveBActionPerformed

    private void txtObjectLengthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObjectLengthFocusLost
        reloadDisplay();
    }//GEN-LAST:event_txtObjectLengthFocusLost

    private void tblHolesAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblHolesAFocusLost
        reloadDisplay();
    }//GEN-LAST:event_tblHolesAFocusLost

    private void tblHolesBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblHolesBFocusLost
        reloadDisplay();
    }//GEN-LAST:event_tblHolesBFocusLost

    private void btnSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAsActionPerformed
        save(true);
    }//GEN-LAST:event_btnSaveAsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Template template = (Template) cboListTemplate.getSelectedItem();
        if (template != null && template.getFileName() != null) {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Xóa mẫu?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                new File(template.getFileName()).delete();
                //reload template list
                Environment.reloadTemplate();
                cboListTemplate.setModel(getTemplateModel());
                onTemplateFolderChange(null);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSetTemplateFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTemplateFolderActionPerformed
        checkAndSave();

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(environment.getSetting().getTemplateFolder()));
        chooser.setDialogTitle("Chọn thư mục chứa mẫu");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            environment.getSetting().setTemplateFolder(chooser.getSelectedFile().getPath());
            lblTemplateFolder.setText(chooser.getSelectedFile().getPath());
            environment.saveSetting();

            //reload template list
            Environment.reloadTemplate();
            cboListTemplate.setModel(getTemplateModel());
            onTemplateFolderChange(null);
        }
    }//GEN-LAST:event_btnSetTemplateFolderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        onTemplateFolderChange(null);
    }//GEN-LAST:event_formWindowOpened

    private void btnZoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomInActionPerformed
        drawPanel.zoomIn();
    }//GEN-LAST:event_btnZoomInActionPerformed

    private void btnZoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZoomOutActionPerformed
        drawPanel.zoomOut();
    }//GEN-LAST:event_btnZoomOutActionPerformed

    private void chkShowPositionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPositionTextActionPerformed
        drawPanel.setIsShowPosition(chkShowPositionText.isSelected());
    }//GEN-LAST:event_chkShowPositionTextActionPerformed

    private void txtObjectWidthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObjectWidthFocusLost
        ((HoleTableModel)tblHolesA.getModel()).setXmax(Float.parseFloat(txtObjectWidth.getText()));
        ((HoleTableModel)tblHolesB.getModel()).setXmax(Float.parseFloat(txtObjectWidth.getText()));
        reloadDisplay();
    }//GEN-LAST:event_txtObjectWidthFocusLost

    private void txtObjectLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObjectLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObjectLengthActionPerformed

    private void onTemplateFolderChange(String selectedFile) {
        lblTemplateFolder.setText(environment.getSetting().getTemplateFolder());
        if (cboListTemplate.getItemCount() > 0) {
            if (selectedFile == null) {
                cboListTemplate.setSelectedIndex(0);
            } else {
                for (int i = 0; i < cboListTemplate.getItemCount(); i++) {
                    if (((Template) cboListTemplate.getItemAt(i)).getFileName().equals(selectedFile)) {
                        cboListTemplate.setSelectedIndex(i);
                        break;
                    }
                }
            }
            lblTemplateFile.setText(((Template) cboListTemplate.getSelectedItem()).getFileName());
        } else {
            btnNewActionPerformed(null);
            lblTemplateFile.setText("");
        }
    }

    private void checkAndSave() {
        if (isDirty) {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Save template?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                save(false);
            }
        }
        isDirty = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddA;
    private javax.swing.JButton btnAddB;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCopyToB;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemoveA;
    private javax.swing.JButton btnRemoveB;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAs;
    private javax.swing.JButton btnSetTemplateFolder;
    private javax.swing.JButton btnZoomIn;
    private javax.swing.JButton btnZoomOut;
    private javax.swing.ButtonGroup buttonGroupA;
    private javax.swing.ButtonGroup buttonGroupB;
    private javax.swing.JComboBox cboListTemplate;
    private javax.swing.JCheckBox chkShowPositionText;
    private punching.ObjectDrawPanel drawPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lblTemplateFile;
    private javax.swing.JLabel lblTemplateFolder;
    private javax.swing.JRadioButton radAX;
    private javax.swing.JRadioButton radAY;
    private javax.swing.JRadioButton radBX;
    private javax.swing.JRadioButton radBY;
    private punching.MyTable tblHolesA;
    private punching.MyTable tblHolesB;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtObjectLength;
    private javax.swing.JFormattedTextField txtObjectWidth;
    // End of variables declaration//GEN-END:variables

    Environment environment = Environment.getInstance();
    boolean isDirty = false;
    float step = 50;

    /**
     * For combo box
     *
     * @return
     */
    private TemplateModel getTemplateModel() {
        Template listTemplate[] = new Template[Environment.getListTemplate().size()];
        for (int i = 0; i < Environment.getListTemplate().size(); i++) {
            listTemplate[i] = Environment.getListTemplate().get(i).clone();
        }
        TemplateModel comboModel = new TemplateModel(listTemplate);
        return comboModel;
    }

    class ComboBoxRenderer extends JLabel
            implements ListCellRenderer {

        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (value != null && value instanceof Template) {
                Template item = (Template) value;
                setText(item.getName());
            }
            return this;
        }

    }

    /**
     * Stop using this because we use MyTable
     */
    private void setCustomTableEditors() {
//        for (int i = 1; i < tblHolesA.getColumnModel().getColumnCount(); i++) {
//            final DefaultCellEditor defaultEditor = (DefaultCellEditor) tblHolesA.getDefaultEditor(tblHolesA.getColumnClass(i));
//            defaultEditor.setClickCountToStart(1);
//        }
//        for (int i = 1; i < tblHolesB.getColumnModel().getColumnCount(); i++) {
//            final DefaultCellEditor defaultEditor = (DefaultCellEditor) tblHolesB.getDefaultEditor(tblHolesB.getColumnClass(i));
//            defaultEditor.setClickCountToStart(1);
//        }

    }

    private void reloadDisplay() {
        Template template = (Template) cboListTemplate.getSelectedItem();
        template.setLength(Float.parseFloat(txtObjectLength.getText()));
        template.setXmax(Float.parseFloat(txtObjectWidth.getText()));
        drawPanel.setTemplate(template);
    }
}
